### ISSUE TITLE
IndentationError: expected an indented block

### ISSUE THREAD

**Issue by hmarrao** [ekergy/tweemanager#2]
He seguido el readme y me ha dado este problema:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 153, in _run_module_as_main
    mod_name, loader, code, fname = _get_main_module_details()
  File "/usr/lib64/python2.7/runpy.py", line 125, in _get_main_module_details
    return _get_module_details(main_name)
  File "/usr/lib64/python2.7/runpy.py", line 113, in _get_module_details
    code = loader.get_code(mod_name)
  File "/usr/lib64/python2.7/pkgutil.py", line 283, in get_code
    self.code = compile(source, self.filename, 'exec')
  File "/home/hmarrao/workspace/tweemanager/tweemanager/__main__.py", line 363
    raise      
        ^
IndentationError: expected an indented block

**Comment by cperales** [comment]
Solved.

Now the problem is the encoding

**Comment by hmarrao** [comment]
tengo este error ahora:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/hmarrao/workspace/tweemanager/tweemanager/__main__.py", line 379, in <module>
    print configdata.get('TwitterAPIcredentials','consumer_key')
  File "/usr/lib64/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'TwitterAPIcredentials'

Que me falta para hacerlo funcionar¿?

**Comment by cperales** [comment]
Añadido al README:

In order to start using this packages, you need to have a config file. A model can be generated:

    $ python tweemanager gendonfig
    
Then, you have to fill the fields in the file with your own data.
