### ISSUE TITLE
Error con configmanager en Python 3.5

### ISSUE THREAD

**Issue by cperales** [ekergy/tweemanager#7]
Estoy ejecutando un script que llama a MongoDB, usando Python 3.5, para poder crear mi propio clasificador, y obtengo este error:

```
Traceback (most recent call last):                                                                                                 
  File "entrenar_de_mongo.py", line 6, in <module>                                                                                 
    from tweemanager.tweetdocument import TweetDocument                                                                            
  File "/home/hmarrao/workspace/tweemanager/Pruebas_Carlos/tweemanager/tweemanager/tweetdocument.py", line 25, in <module>         
    class TweetDocument(mongoengine.DynamicDocument):                                                                              
  File "/home/hmarrao/workspace/tweemanager/.env/lib/python3.5/site-packages/mongoengine/base/metaclasses.py", line 364, in __new__
    new_class._meta['collection'] = collection(new_class)                                                                          
  File "/home/hmarrao/workspace/tweemanager/Pruebas_Carlos/tweemanager/tweemanager/tweetdocument.py", line 14, in create_collection
_name                                                                                                                              
    from configparsermanager import CFGINFO                                                                                        
ImportError: No module named 'configparsermanager'
```

Estoy usando _Python 3.5.1.

**Comment by cperales** [comment]
ACTUALIZACIÓN:

Parece que lo he solventado, aunque no creo que sea lo que debe hacerse. He movido mi script a la carpeta tweemanager, donde se halla el archivo "configparsermanager" (antes estaba una carpeta por encima), y entonces me funciona en Python 3.5. Pero en Python 2.7 me funciona sin tener que introducirme en la carpeta tweemanager.

**Comment by hmarrao** [comment]
Los imports relativos en Python 3.5 y Python 2.7 funcionan de una forma un poco distinta.
Pero basicamente es hacer el import relativo a la ubicación del paquete.
