### ISSUE TITLE
Error importing ConfigParser in Python 2.7

### ISSUE THREAD

**Issue by hmartos** [ekergy/tweemanager#8]
There is an error importing config parser from the following line in Python2.7
`from .configparsermanager import CFGINFO`

Here is the stacktrace:
```
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\wReputationalRisk\reputationalrisk\tweemanager\tweemanager\__main__.py", line 133, in <module>
    utilities.resultshandler = utilities.outputhandler(cmdargs['--output'])
  File "C:/wReputationalRisk/reputationalrisk/tweemanager/tweemanager\utilities.py", line 78, in __init__
    from tweetdocument import TweetDocument
  File "C:/wReputationalRisk/reputationalrisk/tweemanager/tweemanager\tweetdocument.py", line 26, in <module>
    class TweetDocument(mongoengine.DynamicDocument):
  File "C:\Python27\lib\site-packages\mongoengine\base\metaclasses.py", line 363, in __new__
    new_class._meta['collection'] = collection(new_class)
  File "C:/wReputationalRisk/reputationalrisk/tweemanager/tweemanager\tweetdocument.py", line 15, in create_collection_name
    from .configparsermanager import CFGINFO
ValueError: Attempted relative import in non-package`
```

**Comment by hmarrao** [comment]
will change this to a proper config python management!
